import Head from 'next/head'
import AboutPicture from './Components/AboutPicture'
import AboutSectionText from './Components/AboutSectionText'
import Education from './Components/Education'
import Experience from './Components/Experience'
import Layout from './Components/Layout'
import Skills from './Components/Skills'

export default function Home() {
  const prefix = process.env.NEXT_PUBLIC_BASE_PATH || '';
  return (
    <div >
      <Head>
        <title>Asbin Dahal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={prefix + "/favicon.ico"} />
      </Head>

      <main className="">
       <div><AboutPicture /></div>
       <div ><Experience /></div>
       <div><Education /></div>
       <div><Skills /></div>
      </main>
    </div>
  )
}
